apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce #because this only gives permission for us to claim volumes by multiple pods but they have to be on same node as it is the condition by hostpath
  hostPath:
    path: /data
    type: DirectoryOrCreate